FROM    amazonlinux:2 AS artifact_build
RUN     update-ca-trust extract
RUN     yum update -y && yum install -y \
        curl \
        wget \
        awscli \
        sudo \
        unzip \
        git \
        which \
        tar \
        xz \
        java-1.8.0-openjdk-devel.x86_64 
ARG     AWS_DEFAULT_REGION
ARG     AWS_SECRET_ACCESS_KEY 
ARG     AWS_SESSION_TOKEN
ARG     AWS_ACCESS_KEY_ID
# RUN    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
# RUN    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
# RUN    export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
RUN     echo $AWS_ACCESS_KEY_ID 
RUN     echo $AWS_SECRET_ACCESS_KEY 
RUN     echo $AWS_SESSION_TOKEN
RUN   aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
RUN   aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
RUN   aws configure set aws_session_token $AWS_SESSION_TOKEN
RUN   aws sts get-caller-identity 

RUN     aws s3 ls --region us-east-1