version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cx-sam-layer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1a1aqboq18973"
s3_prefix = "cx-sam-layer"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppId=\"\""
image_repositories = []
